### ISSUE TITLE
Unable to retreive characteristics

### ISSUE THREAD

**Issue by Davilka** [Depau/consmart-ble-mqtt#1]
Hi Depau!

Great job!

But, unfortunately, I have troubles with my bulbs.
While trying to connect to it I receive errors:
2020/02/11 00:09:28 handleDeviceFor ▶ DEBUG connecting to 'FF:FF:30:05:94:24'...
2020/02/11 00:09:28 handleDeviceFor ▶ DEBUG connected to 'FF:FF:30:05:94:24', waiting for services...
2020/02/11 00:09:28 handleDeviceFor ▶ ERROR unable to retrieve RGB characteristic for 'FF:FF:30:05:94:24': characteristic not found

I've checked my UUIDs
```const RGBCharUUID string = "0000ffd9-0000-1000-8000-00805f9b34fb"```
```const NotifyCharUUID string = "0000ffd4-0000-1000-8000-00805f9b34fb"```
and they are the same.

Any ideas why I get those errors?

**Comment by depau** [comment]
I do, have you patched bluez as mentioned in the readme?

**Comment by Davilka** [comment]
My fault!

After compiling bluez from source and applying patch bulb seems to be connected!
Yaay!

Does it support changing state of a bulb via mqtt?
I can see only status topic on my broker.

**Comment by depau** [comment]
Hi,
yes, you have to write to the control topics. I should have written that in
the readme, I forgot.
Anyway they're here:
https://github.com/Depau/consmart-ble-mqtt/blob/master/main.go#L100

Color takes a comma-separated RGB value, when saturation is 0 (i.e. all
channels are equal) it uses the bulb's white mode instead. Value can go up
to 255,255,255 which is full white.

Power takes on/off IIRC.

Mode takes one of the modes listed here
<https://github.com/Depau/consmart-ble-mqtt/blob/master/main.go#L100>, then
a comma, then a speed. Speed is a number from 1 to 31 and it's inversely
proportional (don't tell me about it, that's what they came up with
:shrug:). For example, "smooth rainbow,5".

If you happen to find a bluetooth adapter that works consistently fine,
PLEASE LET ME KNOW. I've been struggling with the Raspberry Pi's bluetooth,
after some time, usually from 6 to 12 hours, it stops working and it needs
to be reset.

--
Davide Depau

**Comment by depau** [comment]
I've added the information to the readme and some troubleshooting info, thanks for pointing that out :)

https://github.com/Depau/consmart-ble-mqtt#mqtt-topics

**Comment by Davilka** [comment]
Thanks! It will help newcomers!

But unfortunately I don't see ```control/*``` topics on my broker
My topics are:
- LivingRoom/
  - lights/
    - lamp1/
    online = true
      - status/
        - mode = white
        - color = 0,0,0
        - power = on
    - lamp2/
    online = true
      - status/
         - mode = white
         - color = 0,0,0
         - power = on

**Comment by Davilka** [comment]
Seems that I need to publish to those topics manually (even if it doesn't exist)

After I had published some values to that topics the bulb changed it's state!!! Yaay!

My problem was that those topics haven't been created automatically. It confuses...

**Comment by depau** [comment]
Hi,
The topic is "created" once it's written to. Just send a message to that
topic and it will work.
